version: '3'

services:
  bot:
    build: .
    container_name: tg-autopublisher-bot
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
